// @ts-nocheck
// 主题预设定义文件

export const themePresets = {
    "默认-白天": {
        "--st-chatu8-bg-primary": "#f5f5f5",
        "--st-chatu8-bg-secondary": "#eeeeee",
        "--st-chatu8-bg-tertiary": "#e9e9e9",
        "--st-chatu8-text-primary": "#212529",
        "--st-chatu8-text-secondary": "#6c757d",
        "--st-chatu8-accent-primary": "#007bff",
        "--st-chatu8-accent-secondary": "#0056b3",
        "--st-chatu8-danger-primary": "#dc3545",
        "--st-chatu8-danger-secondary": "#c82333",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#dee2e6",
        "--st-chatu8-dropdown-bg": "#eeeeee",
        "--st-chatu8-dropdown-text": "#212529",
        "--st-chatu8-dropdown-list-bg": "#ffffff",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "默认-夜间": {
        "--st-chatu8-bg-primary": "#0a192f",
        "--st-chatu8-bg-secondary": "#172a45",
        "--st-chatu8-bg-tertiary": "#233554",
        "--st-chatu8-text-primary": "#ff8c00",
        "--st-chatu8-text-secondary": "#8892b0",
        "--st-chatu8-accent-primary": "#ff8c00",
        "--st-chatu8-accent-secondary": "#e67e00",
        "--st-chatu8-danger-primary": "#dc3545",
        "--st-chatu8-danger-secondary": "#c82333",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#233554",
        "--st-chatu8-dropdown-bg": "#172a45",
        "--st-chatu8-dropdown-text": "#ff8c00",
        "--st-chatu8-dropdown-list-bg": "#233554",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "深海蓝": {
        "--st-chatu8-bg-primary": "#0d1b2a",
        "--st-chatu8-bg-secondary": "#1b263b",
        "--st-chatu8-bg-tertiary": "#415a77",
        "--st-chatu8-text-primary": "#e0e1dd",
        "--st-chatu8-text-secondary": "#778da9",
        "--st-chatu8-accent-primary": "#00b4d8",
        "--st-chatu8-accent-secondary": "#0096c7",
        "--st-chatu8-danger-primary": "#ef476f",
        "--st-chatu8-danger-secondary": "#d63d5e",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#415a77",
        "--st-chatu8-dropdown-bg": "#1b263b",
        "--st-chatu8-dropdown-text": "#e0e1dd",
        "--st-chatu8-dropdown-list-bg": "#415a77",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "樱花粉": {
        "--st-chatu8-bg-primary": "#fff5f5",
        "--st-chatu8-bg-secondary": "#ffe4e6",
        "--st-chatu8-bg-tertiary": "#fecdd3",
        "--st-chatu8-text-primary": "#881337",
        "--st-chatu8-text-secondary": "#be185d",
        "--st-chatu8-accent-primary": "#ec4899",
        "--st-chatu8-accent-secondary": "#db2777",
        "--st-chatu8-danger-primary": "#e11d48",
        "--st-chatu8-danger-secondary": "#be123c",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#fda4af",
        "--st-chatu8-dropdown-bg": "#ffe4e6",
        "--st-chatu8-dropdown-text": "#881337",
        "--st-chatu8-dropdown-list-bg": "#fff5f5",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "森林绿": {
        "--st-chatu8-bg-primary": "#f0fdf4",
        "--st-chatu8-bg-secondary": "#dcfce7",
        "--st-chatu8-bg-tertiary": "#bbf7d0",
        "--st-chatu8-text-primary": "#14532d",
        "--st-chatu8-text-secondary": "#166534",
        "--st-chatu8-accent-primary": "#22c55e",
        "--st-chatu8-accent-secondary": "#16a34a",
        "--st-chatu8-danger-primary": "#dc2626",
        "--st-chatu8-danger-secondary": "#b91c1c",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#86efac",
        "--st-chatu8-dropdown-bg": "#dcfce7",
        "--st-chatu8-dropdown-text": "#14532d",
        "--st-chatu8-dropdown-list-bg": "#f0fdf4",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "薰衣草": {
        "--st-chatu8-bg-primary": "#faf5ff",
        "--st-chatu8-bg-secondary": "#f3e8ff",
        "--st-chatu8-bg-tertiary": "#e9d5ff",
        "--st-chatu8-text-primary": "#581c87",
        "--st-chatu8-text-secondary": "#7c3aed",
        "--st-chatu8-accent-primary": "#a855f7",
        "--st-chatu8-accent-secondary": "#9333ea",
        "--st-chatu8-danger-primary": "#dc2626",
        "--st-chatu8-danger-secondary": "#b91c1c",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#d8b4fe",
        "--st-chatu8-dropdown-bg": "#f3e8ff",
        "--st-chatu8-dropdown-text": "#581c87",
        "--st-chatu8-dropdown-list-bg": "#faf5ff",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "琥珀橙": {
        "--st-chatu8-bg-primary": "#fffbeb",
        "--st-chatu8-bg-secondary": "#fef3c7",
        "--st-chatu8-bg-tertiary": "#fde68a",
        "--st-chatu8-text-primary": "#78350f",
        "--st-chatu8-text-secondary": "#b45309",
        "--st-chatu8-accent-primary": "#f59e0b",
        "--st-chatu8-accent-secondary": "#d97706",
        "--st-chatu8-danger-primary": "#dc2626",
        "--st-chatu8-danger-secondary": "#b91c1c",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#fcd34d",
        "--st-chatu8-dropdown-bg": "#fef3c7",
        "--st-chatu8-dropdown-text": "#78350f",
        "--st-chatu8-dropdown-list-bg": "#fffbeb",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "赛博朋克": {
        "--st-chatu8-bg-primary": "#0f0f23",
        "--st-chatu8-bg-secondary": "#1a1a3e",
        "--st-chatu8-bg-tertiary": "#2d2d5a",
        "--st-chatu8-text-primary": "#00ff9f",
        "--st-chatu8-text-secondary": "#ff00ff",
        "--st-chatu8-accent-primary": "#00ffff",
        "--st-chatu8-accent-secondary": "#00cccc",
        "--st-chatu8-danger-primary": "#ff0055",
        "--st-chatu8-danger-secondary": "#cc0044",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#ff00ff",
        "--st-chatu8-dropdown-bg": "#1a1a3e",
        "--st-chatu8-dropdown-text": "#00ff9f",
        "--st-chatu8-dropdown-list-bg": "#2d2d5a",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "莫兰迪": {
        "--st-chatu8-bg-primary": "#e8e4df",
        "--st-chatu8-bg-secondary": "#d4cfc7",
        "--st-chatu8-bg-tertiary": "#c0b9ae",
        "--st-chatu8-text-primary": "#5c574f",
        "--st-chatu8-text-secondary": "#7a746a",
        "--st-chatu8-accent-primary": "#8b9a8b",
        "--st-chatu8-accent-secondary": "#6d7a6d",
        "--st-chatu8-danger-primary": "#c4a4a4",
        "--st-chatu8-danger-secondary": "#a68888",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#ada79d",
        "--st-chatu8-dropdown-bg": "#d4cfc7",
        "--st-chatu8-dropdown-text": "#5c574f",
        "--st-chatu8-dropdown-list-bg": "#e8e4df",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "暗夜紫": {
        "--st-chatu8-bg-primary": "#13111c",
        "--st-chatu8-bg-secondary": "#1e1b2e",
        "--st-chatu8-bg-tertiary": "#2d2844",
        "--st-chatu8-text-primary": "#e2e0f0",
        "--st-chatu8-text-secondary": "#a39ec4",
        "--st-chatu8-accent-primary": "#9d4edd",
        "--st-chatu8-accent-secondary": "#7b2cbf",
        "--st-chatu8-danger-primary": "#ff6b6b",
        "--st-chatu8-danger-secondary": "#ee5a5a",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#3d3764",
        "--st-chatu8-dropdown-bg": "#1e1b2e",
        "--st-chatu8-dropdown-text": "#e2e0f0",
        "--st-chatu8-dropdown-list-bg": "#2d2844",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "冰川蓝": {
        "--st-chatu8-bg-primary": "#f0f9ff",
        "--st-chatu8-bg-secondary": "#e0f2fe",
        "--st-chatu8-bg-tertiary": "#bae6fd",
        "--st-chatu8-text-primary": "#0c4a6e",
        "--st-chatu8-text-secondary": "#0369a1",
        "--st-chatu8-accent-primary": "#0ea5e9",
        "--st-chatu8-accent-secondary": "#0284c7",
        "--st-chatu8-danger-primary": "#ef4444",
        "--st-chatu8-danger-secondary": "#dc2626",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#7dd3fc",
        "--st-chatu8-dropdown-bg": "#e0f2fe",
        "--st-chatu8-dropdown-text": "#0c4a6e",
        "--st-chatu8-dropdown-list-bg": "#f0f9ff",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "暖沙棕": {
        "--st-chatu8-bg-primary": "#fefcfb",
        "--st-chatu8-bg-secondary": "#f5ebe0",
        "--st-chatu8-bg-tertiary": "#e3d5ca",
        "--st-chatu8-text-primary": "#3d2c1e",
        "--st-chatu8-text-secondary": "#6b5344",
        "--st-chatu8-accent-primary": "#b08968",
        "--st-chatu8-accent-secondary": "#9c6644",
        "--st-chatu8-danger-primary": "#cd5c5c",
        "--st-chatu8-danger-secondary": "#b54848",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#d5bdaf",
        "--st-chatu8-dropdown-bg": "#f5ebe0",
        "--st-chatu8-dropdown-text": "#3d2c1e",
        "--st-chatu8-dropdown-list-bg": "#fefcfb",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "极光绿": {
        "--st-chatu8-bg-primary": "#0a1612",
        "--st-chatu8-bg-secondary": "#132520",
        "--st-chatu8-bg-tertiary": "#1d3830",
        "--st-chatu8-text-primary": "#6ee7b7",
        "--st-chatu8-text-secondary": "#34d399",
        "--st-chatu8-accent-primary": "#10b981",
        "--st-chatu8-accent-secondary": "#059669",
        "--st-chatu8-danger-primary": "#f87171",
        "--st-chatu8-danger-secondary": "#ef4444",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#2d5446",
        "--st-chatu8-dropdown-bg": "#132520",
        "--st-chatu8-dropdown-text": "#6ee7b7",
        "--st-chatu8-dropdown-list-bg": "#1d3830",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "玫瑰金": {
        "--st-chatu8-bg-primary": "#1a1515",
        "--st-chatu8-bg-secondary": "#2a2020",
        "--st-chatu8-bg-tertiary": "#3a2d2d",
        "--st-chatu8-text-primary": "#f4d4c4",
        "--st-chatu8-text-secondary": "#d4a494",
        "--st-chatu8-accent-primary": "#e8a090",
        "--st-chatu8-accent-secondary": "#d08878",
        "--st-chatu8-danger-primary": "#e07070",
        "--st-chatu8-danger-secondary": "#c85858",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#5a4a4a",
        "--st-chatu8-dropdown-bg": "#2a2020",
        "--st-chatu8-dropdown-text": "#f4d4c4",
        "--st-chatu8-dropdown-list-bg": "#3a2d2d",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "纯净白": {
        "--st-chatu8-bg-primary": "#ffffff",
        "--st-chatu8-bg-secondary": "#f8f9fa",
        "--st-chatu8-bg-tertiary": "#e9ecef",
        "--st-chatu8-text-primary": "#212529",
        "--st-chatu8-text-secondary": "#495057",
        "--st-chatu8-accent-primary": "#495057",
        "--st-chatu8-accent-secondary": "#343a40",
        "--st-chatu8-danger-primary": "#dc3545",
        "--st-chatu8-danger-secondary": "#c82333",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#ced4da",
        "--st-chatu8-dropdown-bg": "#f8f9fa",
        "--st-chatu8-dropdown-text": "#212529",
        "--st-chatu8-dropdown-list-bg": "#ffffff",
        "--st-chatu8-text-highlight": "#ffffff"
    },
    "墨玉黑": {
        "--st-chatu8-bg-primary": "#121212",
        "--st-chatu8-bg-secondary": "#1e1e1e",
        "--st-chatu8-bg-tertiary": "#2d2d2d",
        "--st-chatu8-text-primary": "#e0e0e0",
        "--st-chatu8-text-secondary": "#a0a0a0",
        "--st-chatu8-accent-primary": "#bb86fc",
        "--st-chatu8-accent-secondary": "#9b66dc",
        "--st-chatu8-danger-primary": "#cf6679",
        "--st-chatu8-danger-secondary": "#b54d5f",
        "--st-chatu8-danger-text": "#ffffff",
        "--st-chatu8-border-color": "#3d3d3d",
        "--st-chatu8-dropdown-bg": "#1e1e1e",
        "--st-chatu8-dropdown-text": "#e0e0e0",
        "--st-chatu8-dropdown-list-bg": "#2d2d2d",
        "--st-chatu8-text-highlight": "#ffffff"
    }
};

// 获取所有预设主题的名称列表
export function getThemePresetNames() {
    return Object.keys(themePresets);
}

// 获取指定名称的主题预设
export function getThemePreset(name) {
    return themePresets[name] || null;
}

// 判断主题是否为浅色主题
export function isLightTheme(themeName) {
    const lightThemes = ['默认-白天', '樱花粉', '森林绿', '薰衣草', '琥珀橙', '莫兰迪', '冰川蓝', '暖沙棕', '纯净白'];
    return lightThemes.includes(themeName);
}
